config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/auth/github', as: 'github_login'
  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/dashboard', to: 'dashboard#index'

  resources :repos, only: [:index]
  resources :orgs, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commit.rb
class Commit

  attr_reader :message

  def initialize(message)
    @message = message
  end

  def self.find_commits(token, login)
    raw_events = GithubService.commits(token, login)
    push_events = raw_events.select { |event| event[:type] == "PushEvent" }
    repos = push_events.map { |event| (event[:repo][:name]).split('/').pop }

    commits = push_events.map.with_index do |event, n|
      raw_commits = event[:payload][:commits]
      raw_commits.map do |raw_commit|
        [repos[n], (raw_commit[:message]).sub(/\n\n/, '>').split('>').shift]
      end
    end.flatten(1)

    create_commits(commits)
  end

  def self.create_commits(commits)
    commits.map { |commit| commit.join(': ') }.map { |commit| new(commit) }
  end

end

app/models/github_user.rb
class GithubUser

  attr_reader :token, :login, :name, :avatar_url, :starred_url, :followers_url, :following_url

  def initialize(attrs = {}, token)
    @attrs = attrs
    @token = token
    @login = attrs[:login]
    @name = attrs[:name]
    @avatar_url = attrs[:avatar_url]
    @starred_url = attrs[:starred_url]
    @followers_url = attrs[:followers_url]
    @following_url = attrs[:following_url]
  end

  def self.find_github_user(token)
    raw_githubuser = GithubService.github_user_by(token)
    new(raw_githubuser, token)
  end

  def starred(token)
    raw_starred = GithubService.starred(token)
  end

  def followers(token)
    GithubService.followers(token).map(&create_github_user(token))
  end

  def following(token)
    GithubService.following(token).map(&create_github_user(token))
  end

  def repos
    Repo.find_repos(token)
  end

  def orgs
    Org.find_orgs(token)
  end

  def commits
    Commit.find_commits(token, login)
  end

  def create_github_user(token)
    -> user { GithubUser.new(user, token) }
  end

  private

  attr_reader :attrs

end

app/models/org.rb
class Org

  def self.find_orgs(token)
    GithubService.orgs(token)
  end

end

app/models/repo.rb
class Repo

  attr_reader :token, :name, :owner

  def initialize(token, attrs={})
    @token = token
    @attrs = attrs
    @name = attrs[:name]
    @owner = attrs[:owner][:login]
  end

  def self.find_repos(token)
    GithubService.repos(token).select { |repo| repo[:owner][:login] == "NessEFC" }.map { |repo| Repo.new(token, repo) }
  end

  private

  attr_reader :attrs

end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid          = auth_info.uid
      new_user.username     = auth_info.info.nickname
      new_user.token        = auth_info.credentials.token
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = GithubUser.find_github_user(current_user.token)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  def index
    @orgs = GithubUser.find_github_user(current_user.token).orgs
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    @repos = GithubUser.find_github_user(current_user.token).repos
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
      flash[:success] = "You are logged in as #{user.username}"
    end
    redirect_to dashboard_path
  end

  def destroy
    session.clear
    flash[:success] = "Successfully logged out. Goodbye!"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<div class="avatar"><%= image_tag(@user.avatar_url) %></div>

<h3><%= @user.name %></h3>

<h4><%= @user.login %></h4><br>

<p>Stars: <%= @user.starred(current_user.token).count %></p><br>

<p>Followers(<%= @user.followers(current_user.token).count %>):
<% @user.followers(current_user.token).each do |follower| %>
  <li><%= follower.login %></li>
<% end %></p>

<p>Following(<%= @user.following(current_user.token).count %>):
<% @user.following(current_user.token).each do |user| %>
  <li><%= user.login %></li>
<% end %></p><br>

<p>Recent Commits: <br><% @user.commits.each do |commit| %>
  <li><%= commit.message %></li>
<% end %></p>

app/views/home/index.html.erb
<h1>Howdy</h1>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="navbar-header">
    <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-left">
      <!-- <div class="brand-img"><a href="/" class="navbar-left"><%= image_tag "icon.png" %></a></div> -->
      <a class="navbar-brand" href="/">APICurious</a>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <p class="navbar-text">Logged in as <%= current_user.username %></p>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in with GitHub", github_login_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apicurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/orgs/index.html.erb
<% if @orgs.empty? %>
  <p>You do not belong to any organizations.</p>
<% end %>

app/views/repos/index.html.erb
<h1>Repos: <%= @repos.count %></h1><br>
<% @repos.each do |repo| %>
  <%= repo.name %><br>
<% end %>